// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbq7HNEBhFMLIMJ8tRWPbx1CwxZSk8b2s',
    appId: '1:269481513714:web:f7e0ab6153232e6fe9b66b',
    messagingSenderId: '269481513714',
    projectId: 'snsmodoki',
    authDomain: 'snsmodoki.firebaseapp.com',
    storageBucket: 'snsmodoki.appspot.com',
    measurementId: 'G-KCN953F7LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrd8rk3IBJFA2FCnF6Bdq_OPifWIHneJU',
    appId: '1:269481513714:android:b8e08082f4e1423fe9b66b',
    messagingSenderId: '269481513714',
    projectId: 'snsmodoki',
    storageBucket: 'snsmodoki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtKmM6_nvga9HWSaKtx9Ux9j2YOLatLtI',
    appId: '1:269481513714:ios:b2a75ed12de675a0e9b66b',
    messagingSenderId: '269481513714',
    projectId: 'snsmodoki',
    storageBucket: 'snsmodoki.appspot.com',
    iosClientId: '269481513714-rfa8m9qgrplkfnjjs9ll6vl5qtuu1u6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtKmM6_nvga9HWSaKtx9Ux9j2YOLatLtI',
    appId: '1:269481513714:ios:b2a75ed12de675a0e9b66b',
    messagingSenderId: '269481513714',
    projectId: 'snsmodoki',
    storageBucket: 'snsmodoki.appspot.com',
    iosClientId: '269481513714-rfa8m9qgrplkfnjjs9ll6vl5qtuu1u6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
